name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy Cloud Function v2
        run: |
          gcloud functions deploy process_file_v2 \
            --gen2 \
            --runtime python312 \
            --trigger-topic=${{ secrets.GCP_PUBSUB_TOPIC }} \
            --entry-point process_file_v2 \
            --region=${{ secrets.GCP_REGION }} \
            --set-env-vars BLACKLIST_API_KEY=${{ secrets.BLACKLIST_API_KEY }},OUTPUT_BUCKET=${{ secrets.OUTPUT_BUCKET }}
